process.argv[2] = 'lib';
const { run } = await import('./probe.mjs');
const bad = [
  // reversed / wrong roles
  ['g-slain-01', 'Tywin Lannister falls to Robb Stark at the Twins', null, 'bad'],
  ['g-slain-01', 'Tywin Lannister cut down by Robb Stark at the Twins', null, 'bad'],
  ['g-slain-01', 'Tywin Lannister kills Robb Stark at the Twins', null, 'good'],
  ['g-slain-01', 'Robb Stark kills Tywin Lannister at the Twins', null, 'bad'],
  ['g-slain-01', 'Robb Stark cuts down Tywin Lannister at the Twins', null, 'bad'],
  ['g-battle-01', 'Roose Bolton crushes Tywin Lannister at the Twins', null, 'bad'],
  ['g-battle-01', 'Roose Bolton wins at the Twins', null, 'bad'],
  ['g-battle-01', 'Bolton host wins the field at the Twins', null, 'bad'],
  ['g-battle-01', 'Tywin Lannister loses at the Twins', null, 'bad'],
  ['g-battle-01', 'Lannister host broken at the Twins', null, 'bad'],
  ['g-capture-01', 'Robb Stark falls into Lannister hands near Riverrun', null, 'bad'],
  ['g-capture-01', 'Robb Stark takes Jaime Lannister prisoner near Riverrun', null, 'good'],
  ['g-capture-01', 'Jaime Lannister takes Robb Stark prisoner near Riverrun', null, 'bad'],
  ['g-capture-01', 'Jaime Lannister seizes Robb Stark near Riverrun', null, 'bad'],
  ['g-capture-01', 'Jaime Lannister escapes Robb Stark near Riverrun', null, 'bad'],
  ['g-exec-01', 'Ser Amory Lorch beheads Eddard Stark at Winterfell', null, 'bad'],
  ['g-exec-01', 'Ser Amory Lorch executed by Stark at Winterfell', null, 'good'],
  ['g-exec-01', 'Eddard Stark loses his head at Winterfell', null, 'bad'],
  ['g-exec-01', 'Eddard Stark put to death at Winterfell', null, 'bad'],
  ['g-siege-01', 'Riverrun lays siege to Jaime Lannister', null, 'bad'],
  ['g-siege-01', 'Riverrun surrounds Jaime Lannister', null, 'bad'],
  ['g-siege-01', 'Jaime Lannister lifts the siege of Riverrun', null, 'bad'],
  ['g-siege-01', 'Riverrun opens its gates to Jaime Lannister', null, 'bad'],
  ['g-siege-01', 'Jaime Lannister storms Riverrun', null, 'bad'],
  ['g-siege-01', 'Jaime Lannister takes Riverrun', null, 'bad'],
  // invented
  ['g-refusal-01', 'Lady Hornwood refuses Robb Stark\'s summons', null, 'bad'],
  ['g-refusal-01', 'Lady Hornwood refuses Stark\'s summons at Winterfell', null, 'good'],
  ['g-refusal-01', 'Lady Hornwood refuses the Lannister summons', null, 'bad'],
  ['g-refusal-01', 'Lady Hornwood refuses King Robert\'s summons', null, 'bad'],
  ['g-refusal-01', 'Lady Hornwood refuses Stark\'s summons out of fear of the Boltons', null, 'bad'],
  ['g-refusal-01', 'Lady Hornwood refuses Stark\'s summons at Riverrun', null, 'bad'],
  ['g-refusal-01', 'Lady Hornwood refuses Stark\'s summons, says maester Luwin', null, 'bad'],
  ['g-refusal-01', 'Lady Hornwood refuses the Starks and the Boltons', null, 'bad'],
  ['g-refusal-01', 'Lady Hornwood refuses the Kingslayer', null, 'bad'],
  ['g-refusal-01', 'Lady Hornwood refuses the Hand of the King', null, 'bad'],
  ['g-refusal-01', 'Lady Hornwood refuses Stark\'s call and Ser Barristan weeps', null, 'bad'],
  // numbers / hidden
  ['g-siege-01', 'Twenty thousand Lannisters besiege Riverrun', null, 'bad'],
  ['g-siege-01', 'Sixty Lannisters besiege Riverrun', null, 'bad'],
  ['g-siege-01', 'Two hundred thousand Lannisters besiege Riverrun', null, 'bad'],
  ['g-siege-01', 'Lannister host of fifteen thousand besieges Riverrun for two weeks', null, 'bad'],
  // jargon / boilerplate variants
  ['g-muster-02', 'Umber host is mustered at Last Hearth', null, 'bad'],
  ['g-muster-02', 'Lord Umber raises a host of levies at Last Hearth', null, 'bad'],
  ['g-muster-02', 'Lord Umber musters his levy at Last Hearth', null, 'bad'],
  ['g-muster-02', 'Umber raises 2k men at Last Hearth', null, 'bad'],
  ['g-muster-02', 'Lord Umber\'s host numbers two thousand at Last Hearth', null, 'bad'],
  ['g-muster-02', 'Lord Umber answers the call, importance high', null, 'bad'],
  ['g-muster-02', 'Turn 3: Lord Umber raises men at Last Hearth', null, 'bad'],
  ['g-muster-02', 'Lord Umber raises men at Last Hearth [muster]', null, 'bad'],
  ['g-muster-02', 'Lord Umber rides north at Last Hearth', null, 'good'],
  ['g-muster-02', 'Lord Umber, a sworn bannerman, raises men at Last Hearth', null, 'good'],
  ['g-muster-02', 'Lord Umber raises men at Last Hearth, a fact of note', null, 'bad'],
  ['g-muster-02', 'Lord Umber "the Greatjon" raises men at Last Hearth', null, 'bad'],
  ['g-muster-02', 'lord umber raises men at last hearth', null, 'good'],
  ['g-muster-02', 'LORD UMBER RAISES MEN AT LAST HEARTH!', null, 'bad'],
  ['g-muster-02', 'Lord Umber raises men at Last Hearth!', null, 'bad'],
  ['g-muster-02', 'Lord Umber raises men at Last Hearth?', null, 'bad'],
  ['g-muster-02', 'Lord Umber raises men at Last Hearth, and', null, 'bad'],
  ['g-muster-02', 'Lord Umber raises men\nat Last Hearth', null, 'good'],
  ['g-muster-02', 'Lord Umber raises men at Last Hearth &c.', null, 'bad'],
  ['g-muster-02', 'Lord Umber raises men at Last Hearth #war', null, 'bad'],
  ['g-muster-02', 'Lord Umber raises men at Last Hearth \u{1F5E1}', null, 'bad'],
  ['g-muster-02', 'Lord Umber raises men at Last Hearth <b>now</b>', null, 'bad'],
  ['g-muster-02', 'Lord Umber raises men at Last Hearth *breaking*', null, 'bad'],
  ['g-muster-02', 'Lord Umber raises men at Last Hearth - report', null, 'bad'],
  ['g-muster-02', 'Lord Umber raises men at Last Hearth / Stark army', null, 'bad'],
  // tense/quality
  ['g-omen-02', 'Karhold has a summer snow', null, 'bad'],
  ['g-omen-02', 'Karhold Karhold Karhold Karhold', null, 'bad'],
  ['g-omen-02', 'Snow is on the ground at Karhold', null, 'good'],
  ['g-omen-02', 'Something happens at Karhold', null, 'bad'],
  ['g-omen-02', 'A thing occurs at Karhold', null, 'bad'],
  ['g-omen-02', 'Karhold is a place where snow fell', null, 'bad'],
  ['g-omen-02', 'Karhold reports news', null, 'bad'],
  ['g-omen-02', 'An event unfolds at Karhold', null, 'bad'],
];
run('BAD / mixed', bad);
