process.env.WC_PROVIDER = 'mock';
const R = '/home/user/wc-s2/public/js/';
const { sampleRealm } = await import(R + 'engine/realm/stats.js');
const { realmViewFor } = await import(R + 'engine/realm/view.js');
const { createInitialState, applyChanges } = await import(R + 'shared/world.js');
const { addDays, dayNumber } = await import(R + 'engine/time.js');
const { withRng } = await import(R + 'engine/rng.js');
const K = await import(R + 'engine/knowledge.js');
const world = (house = 'stark', seed = 298) => createInitialState('agot_298', house, { seed });
const clone = (x) => JSON.parse(JSON.stringify(x));
const tick = (s, days = 7) => { s.meta.turn += 1; s.meta.date = addDays(s.meta.date, days); sampleRealm(s); withRng(s, () => K.updateKnowledge(s, 'stark')); return s; };
const s = world(); for (let i = 0; i < 3; i++) tick(s);
const OPTS = [];
for (const lens of ['strength','economy','land']) for (const scope of ['great','all','mine','war']) for (const realm of [false,true]) OPTS.push({lens, scope, realm});
for (const h of Object.keys(s.houses)) OPTS.push({house: h, scope: 'all'});
const json = (x) => JSON.stringify(x);
const base = OPTS.map(o => json(realmViewFor(s, 'stark', o)));
const friends = K.friendsOf(s, 'stark');
console.log('friends', [...friends]);
console.log('houses', Object.keys(s.houses).length, 'ranks', Object.entries(Object.values(s.houses).reduce((a,h)=>(a[h.rank]=(a[h.rank]||0)+1,a),{})));
const v = realmViewFor(s,'stark',{scope:'all'});
console.log('all rows', v.rows.length, v.rows.map(r=>r.house).join(','));
function tryMut(name, fn) {
  const t = clone(s); fn(t);
  const diffs = [];
  OPTS.forEach((o,i) => { const a = json(realmViewFor(t,'stark',o)); if (a !== base[i]) diffs.push(json(o)); });
  console.log((diffs.length ? 'CHANGES ' : 'same    ') + name + (diffs.length ? '  (' + diffs.length + ' views, e.g. ' + diffs[0] + ')' : ''));
}
const others = (t) => Object.values(t.houses).filter(h => !friends.has(h.id));
const farHold = (t) => Object.values(t.holdings).filter(h => !friends.has(h.owner));
tryMut('holdings.prosperity far', t => farHold(t).forEach(h => h.prosperity = 3));
tryMut('holdings.unrest far', t => farHold(t).forEach(h => h.unrest = 99));
tryMut('holdings.status besieged far', t => farHold(t).forEach(h => h.status = 'besieged'));
tryMut('holdings.devastation far', t => farHold(t).forEach(h => h.devastation = 90));
tryMut('holdings.population far', t => farHold(t).forEach(h => h.population = Math.round(h.population*3)));
tryMut('holdings.owner swap far (lannister<->tyrell)', t => Object.values(t.holdings).forEach(h => { if (h.owner==='lannister') h.owner='tyrell'; }));
tryMut('holdings.blockade far', t => farHold(t).forEach(h => h.blockade = true));
tryMut('house.lord far (dead)', t => { for (const h of others(t)) if (h.lord && t.characters[h.lord]) t.characters[h.lord].alive = false; });
tryMut('house.status extinct tyrell', t => { t.houses.tyrell.status = 'extinct'; });
tryMut('house.liege far change', t => { t.houses.tully && (t.houses.frey.liege = 'lannister'); });
tryMut('house.policy.tax far', t => others(t).forEach(h => { h.policy = {...(h.policy||{}), tax: 'harsh'}; }));
tryMut('war sides: lannister joins on stark? unknown war', t => t.wars.push({ id:'w_x', name:'X', attackers:['martell'], defenders:['lannister'], status:'ongoing', score: 5 }));
tryMut('existing wars: scores', t => t.wars.forEach(w => w.score = 77));
tryMut('existing wars: status ended', t => t.wars.forEach(w => w.status = 'ended'));
tryMut('existing wars: add attacker', t => t.wars.forEach(w => w.attackers.push('tyrell')));
console.log('wars', s.wars.map(w => `${w.id} ${w.name} ${w.attackers}|${w.defenders} ${w.status}`));
tryMut('knowledge of other houses', t => { t.knowledge.lannister = { realm: { stark: { obs: [{ day: 1, turn: 1, via: 'seen', v: { swords: 999999 } }] } }, parties: {}, facts: {}, spies: {}, beliefs: [] }; });
tryMut('minds', t => { t.minds = { last: { tywin_lannister: 1 } }; });
tryMut('economy loans far', t => t.economy.loans.forEach(l => l.amount *= 100));
tryMut('parties: garrisons far men', t => Object.values(t.parties).forEach(a => { if (!friends.has(a.owner) && !K.seesParty(t,'stark',a)) a.men = 99999; }));
tryMut('parties: fleets far ships', t => Object.values(t.parties).forEach(a => { if (!friends.has(a.owner) && !K.seesParty(t,'stark',a)) a.ships = 99; }));
tryMut('parties owner swap unseen', t => Object.values(t.parties).forEach(a => { if (!friends.has(a.owner) && !K.seesParty(t,'stark',a)) a.owner = 'lannister'; }));
tryMut('state.world.season', t => { t.world.season = t.world.season === 'winter' ? 'summer' : 'winter'; });
tryMut('house.levyCap far', t => others(t).forEach(h => h.levyCap = 1));
tryMut('house.figures far', t => others(t).forEach(h => Object.values(h.figures).forEach(f => f.v = 12345)));
tryMut('house.ledger far', t => others(t).forEach(h => { h.ledger = [{x:1}]; }));
tryMut('house.rank far change (tyrell->minor)', t => { t.houses.tyrell.rank = 'minor'; });
tryMut('characters far kin die', t => Object.values(t.characters).forEach(c => { if (c.house && !friends.has(c.house)) c.alive = false; }));
tryMut('mine depletion state', t => { t.economy.depletion = { lannister: 0.1 }; t.economy.mines = {lannister: 0}; });
tryMut('realmStats other houses', t => t.realmStats.samples.forEach(sm => Object.keys(sm.h).forEach(h => { if (!friends.has(h)) sm.h[h] = sm.h[h].map(()=>1); })));
tryMut('realmStats ally/sworn houses (truth series)', t => t.realmStats.samples.forEach(sm => Object.keys(sm.h).forEach(h => { if (friends.has(h) && h!=='stark') sm.h[h] = sm.h[h].map((x)=>x*2); })));
tryMut('pacts other', t => t.pacts.push({ id:'p9', a:'lannister', b:'tyrell', type:'alliance', status:'active' }));
