import { createInitialState } from '/home/user/wc-s2/public/js/shared/world.js';
import { friendsOf, eyesOf, seesParty } from '/home/user/wc-s2/public/js/engine/knowledge.js';
import { standing } from '/home/user/wc-s2/public/js/shared/standing.js';
import { forces } from '/home/user/wc-s2/public/js/engine/parties.js';
import { ECONOMY } from '/home/user/wc-s2/public/data/balance.js';
const s = createInitialState('agot_298','stark',{seed:298});
console.log('stark liege', s.houses.stark.liege, [...friendsOf(s,'stark')].join(','));
console.log('pacts', JSON.stringify(s.pacts).slice(0,600));
console.log('economy loans', JSON.stringify(s.economy.loans).slice(0,400));
console.log('mines', JSON.stringify(ECONOMY.mines), JSON.stringify(ECONOMY.mineDepletion));
console.log('wars', JSON.stringify(s.wars));
console.log(JSON.stringify(standing(s,'stark')), JSON.stringify(standing(s,'lannister')));
console.log(s.standing);
console.log(JSON.stringify(s.houses.lannister.figures));
const E = eyesOf(s,'stark'); 
const hosts = forces(s).map(a=>a.id+':'+a.owner+':'+a.men+':'+seesParty(s,'stark',a,E)); console.log(hosts.join(' '));
console.log(Object.keys(s.knowledge.stark.parties).length, JSON.stringify(s.knowledge.stark).slice(0,300));
console.log('MUSTER?'); 
import * as bal from '/home/user/wc-s2/public/data/balance.js'; console.log(Object.keys(bal));
console.log(Object.values(s.houses).filter(h=>h.rank==='minor'&&!h.liege).length);
