process.env.WC_PROVIDER='mock';
const R='/home/user/wc-s2/public/js/';
const { createInitialState } = await import(R+'shared/world.js');
const { sampleRealm } = await import(R+'engine/realm/stats.js');
const { realmViewFor } = await import(R+'engine/realm/view.js');
const { figuresOf } = await import(R+'engine/realm/figures.js');
const { withRng } = await import(R+'engine/rng.js');
const { addDays } = await import(R+'engine/time.js');
const K = await import(R+'engine/knowledge.js');
const { standing } = await import(R+'shared/standing.js');
const { project } = await import(R+'shared/economy.js');
const s = createInitialState('agot_298','stark',{seed:298});
const tick = (s, days=7) => { s.meta.turn += 1; s.meta.date = addDays(s.meta.date, days); sampleRealm(s); withRng(s, () => K.updateKnowledge(s, 'stark')); };
for (let i = 0; i < 12; i++) tick(s);
const med = (f, n = 15) => { const a = Array.from({ length: n }, () => { const t = performance.now(); f(); return performance.now() - t; }).sort((x, y) => x - y); return `${a[n >> 1].toFixed(1)} ms (best ${a[0].toFixed(1)}, worst ${a.at(-1).toFixed(1)})`; };
console.log('sampleRealm          ', med(() => sampleRealm(s)));
const ids = Object.keys(s.houses);
console.log('  of which standing()', med(() => ids.forEach((h) => standing(s, h))));
console.log('  of which project() ', med(() => ids.forEach((h) => project(s, h))));
console.log('updateKnowledge      ', med(() => K.updateKnowledge(s, 'stark')));
for (const o of [{}, { scope: 'all' }, { scope: 'all', lens: 'economy' }, { scope: 'all', lens: 'land', realm: true }, { scope: 'all', house: 'lannister' }]) console.log('realmViewFor', JSON.stringify(o).padEnd(42), med(() => realmViewFor(s, 'stark', o)));
