process.argv[2] = 'lib';
const { run } = await import('./probe.mjs');
run('present-tense verbs outside the lexicon (good headlines)', [
  ['g-march-02', 'Lord Karstark names Harrion his heir at Karhold', null, 'good'],
  ['g-refusal-01', 'Lady Hornwood threatens to hold her men back', null, 'good'],
  ['g-siege-01', 'Jaime Lannister rings Riverrun with fifteen thousand men', null, 'good'],
  ['g-battle-01', 'Tywin Lannister drives Roose Bolton from the Twins', null, 'good'],
  ['g-capture-01', 'Robb Stark jails Jaime Lannister near Riverrun', null, 'good'],
  ['g-capture-01', 'Robb Stark arrests Jaime Lannister near Riverrun', null, 'good'],
  ['g-battle-01', 'Tywin Lannister makes Roose Bolton run at the Twins', null, 'good'],
  ['g-battle-01', 'Tywin Lannister hits Roose Bolton hard at the Twins', null, 'good'],
  ['g-battle-01', 'Tywin Lannister shatters Roose Bolton at the Twins', null, 'good'],
  ['g-battle-01', 'Tywin Lannister smashes Roose Bolton at the Twins', null, 'good'],
  ['g-battle-01', 'Roose Bolton is beaten by Tywin Lannister at the Twins', null, 'good'],
  ['g-battle-01', 'Roose Bolton loses to Tywin Lannister at the Twins', null, 'good'],
  ['g-battle-01', 'Tywin Lannister defeats Roose Bolton at the Twins', null, 'good'],
  ['g-battle-01', 'Roose Bolton is driven from the Twins by Tywin Lannister', null, 'good'],
  ['g-battle-01', 'Roose Bolton flees the Twins before Tywin Lannister', null, 'good'],
  ['g-battle-01', 'Roose Bolton loses the Twins to Tywin Lannister', null, 'good'],
  ['g-battle-01', 'Tywin Lannister wins at the Twins', null, 'good'],
  ['g-battle-01', 'Tywin Lannister triumphs over Roose Bolton at the Twins', null, 'good'],
  ['g-battle-01', 'Roose Bolton yields to Tywin Lannister at the Twins', null, 'good'],
  ['g-battle-01', 'Roose Bolton falls back from the Twins before Tywin Lannister', null, 'good'],
  ['g-battle-01', 'Roose Bolton retreats from the Twins', null, 'good'],
  ['g-battle-01', 'Roose Bolton is routed at the Twins', null, 'good'],
  ['g-battle-01', 'Roose Bolton and Tywin Lannister clash at the Twins', null, 'good'],
  ['g-battle-01', 'Roose Bolton and Tywin Lannister meet at the Twins', null, 'good'],
  ['g-battle-01', 'Roose Bolton and Tywin Lannister fight at the Twins', null, 'good'],
]);
